defaults:
    - dataset@dataset: Leaves-PNAS
    - model@model: resnet_50_v2
    
    - db@db : sqlite
    
fold_id: null

batch_size: 16
buffer_size: 200
num_epochs: 150
frozen_layers: null
augmentations:
    - flip: 1.0

seed: 45
use_tfrecords: true
samples_per_shard: 300
    

neptune_project_name: "jacobarose/sandbox"
neptune_experiment_dir: "/media/data/jacob/sandbox_logs"

experiment_name: ???
experiment_dir: ???
experiment_start_time: null
restore_last: True
    
model_dir: null
tfrecord_dir: null
results_dir: null
saved_model_path: null
checkpoints_path: null
n_jobs: 1
num_gpus: 1
gpu_num: null

run_description: ""