# @package _group_

params:
    model_name: 'resnet_50_v2'
    weights: null
    input_shape: [256,256,'${params.num_channels}']
    num_classes: null
    num_channels: 3
    optimizer: 'Adam'
    loss: 'categorical_crossentropy'
    lr: 4.0e-5
    lr_decay: 1.0
    lr_decay_epochs: 10
    lr_momentum: null
    regularization:
        l2: 1e-6
    METRICS: ['f1','accuracy']

    head_layers: [256,128]
    frozen_layers: null

    preprocess_input:
        _target_: tensorflow.keras.applications.imagenet_utils
        data_format: 'channels_last'
        mode: 'tf'

        # TODO Look up actual mode for resnet preprocess_input