# @package _group_

params:
    model_name: 'resnet_50_v2'
    weights: 'imagenet'
    input_shape: [299,299,3]
    optimizer: 'Adam'
    loss: 'categorical_crossentropy'
    lr: 4.0e-5 #Karpathy recommends 3e-4
    lr_decay: 1.0
    lr_decay_epochs: 10
    lr_momentum: null
    regularization:
        l2: 4.0e-10
    METRICS: ['f1','accuracy']

    head_layers: [256,128]

    preprocess_input:
        _target_: tensorflow.keras.applications.resnet_v2