# @package _group_

model_name: 'vgg16'
optimizer: 'Adam'
loss: 'categorical_crossentropy'
lr: 4.0e-5
lr_decay: 1.0
lr_decay_interval: 10
lr_momentum: null
regularization:
    l1: null
METRICS: ['f1','accuracy']

head_layers: [512,256]