# @package _group_

params:
  extract:
    fold_id: 0
    fold_dir: '/home/jacob/projects/paleoai_data/paleoai_data/v0_2/data/staged_data/Fossil_family_100/ksplit_2'
    dataset_name: 'Fossil_family_100'
    num_classes: 9
    num_samples: 3559
    threshold: 
    val_split: 0.0
    include_classes: []
    exclude_classes: ['notcataloged','notcatalogued', 'II. IDs, families uncertain', 'Unidentified']

  training:
    augmentations:
      - flip: 0.0
    steps_per_epoch: null
    validation_steps: null
    use_tfrecords: false
    samples_per_shard: 300


  testing:
    include_subsets: ['test'] # include ['train','test'] to concatenate them for testing
    eval_performance_w_sklearn: true