# @package _group_

params:
  extract:
    fold_id: 0
    fold_dir: '/home/jacob/projects/paleoai_data/paleoai_data/v0_2/data/staged_data/Leaves_in_PNAS_family_100/ksplit_2'
    dataset_name: 'Leaves_in_PNAS_family_100'
    num_classes: 12
    num_samples: 2501
    threshold: 100
    include_classes: []
    exclude_classes: ['notcataloged','notcatalogued', 'II. IDs, families uncertain', 'Unidentified']