# @package _group_

params:
  extract:
    fold_id: 0
    fold_dir: '/home/jacob/projects/paleoai_data/paleoai_data/v0_2/data/staged_data/PNAS_family_50/ksplit_2'
    dataset_name: 'PNAS_family_50'
    num_classes: null
    threshold: 50
    description: "PNAS dataset, limited to families with >50 images/class."

