# @package _group_

params:
  dataset:
    fold_id: 0
    fold_dir: '/home/jacob/projects/paleoai_data/paleoai_data/v0_2/data/staged_data/Leaves_in_PNAS_family_100/ksplit_2'
    dataset_name: 'Leaves_in_PNAS_family_100'
    num_classes: null
    threshold: 100
