defaults:
    - model@stage_0/model: resnet_50_v2
    - dataset@stage_0/dataset: Leaves-PNAS
    
    - model@stage_1/model: resnet_50_v2
    - dataset@stage_1/dataset: Fossil
    
    
stage_0:
    training:
        batch_size: 16
        buffer_size: 200
        num_epochs: 150
        frozen_layers: null
        augmentations:
            - flip: 1.0
    misc:
        seed: 45
        use_tfrecords: true
        samples_per_shard: 500
    
    
    
experiment:
    neptune_project_name: "jacobarose/sandbox"
    neptune_experiment_dir: "/media/data/jacob/sandbox_logs"
    experiment_name: ???
    experiment_dir: ???
    experiment_start_time: ???
    restore_last: True
    
    
    
    
pipeline:
    - stage_0
    - stage_1

log_dir: ???
model_dir: ???
tfrecord_dir: ???
results_dir: ???
saved_model_path: ???
checkpoints_path: ???
n_jobs: 1
num_gpus: 1