experiment:
    neptune_project_name: "jacobarose/sandbox"
    neptune_experiment_dir: "/media/data/jacob/sandbox_logs"
    experiment_name: ???
    experiment_dir: ???
    experiment_start_time: ???

stage_0:
    tfrecord_dir: ???
    dataset:
        fold_dir: '/home/jacob/projects/paleoai_data/paleoai_data/v0_2/data/staged_data/Leaves-PNAS/ksplit_10'
        dataset_name: 'Leaves-PNAS'
        num_classes: ???
        threshold: 10
        color_mode: 'grayscale'
        num_channels: 3
        target_size: [512,512]
        splits:
            train: 0.5
            validation: 0.5
        include_classes: []
        exclude_classes: ['notcataloged','notcatalogued', 'II. IDs, families uncertain', 'Unidentified']
    model:
        model_name: 'resnet_50_v2'
        optimizer: 'Adam'
        loss: 'categorical_crossentropy'
        lr: 4.0e-5
        regularization:
            l1: 3e-4
        METRICS: ['accuracy','precision','recall']

    training:
        batch_size: 16
        buffer_size: 200
        num_epochs: 150
        frozen_layers: null
        augmentations:
            - flip: 1.0
    misc:
        seed: 45
        use_tfrecords: true
        samples_per_shard: 500

stage_1:
    tfrecord_dir: ???
    dataset:
        fold_dir: '/home/jacob/projects/paleoai_data/paleoai_data/v0_2/data/staged_data/PNAS/ksplit_10'
        dataset_name: 'PNAS'
        num_classes: ???
        threshold: 10
        color_mode: 'grayscale'
        num_channels: 3
        target_size: (512,512)
        splits:
            train: 0.5
            validation: 0.5
        exclude_classes: ['notcataloged','notcatalogued', 'II. IDs, families uncertain', 'Unidentified']
    model:
        model_name: 'resnet_50_v2'
        optimizer: 'Adam'
        loss: 'categorical_crossentropy'
        lr: 4.0e-5
        regularization:
            l1: 3e-4
        METRICS: ['accuracy','precision','recall']

    training:
        batch_size: 16
        buffer_size: 200
        num_epochs: 150
        frozen_layers: null
        augmentations:
            - flip: 1.0
    misc:
        seed: 45
        use_tfrecords: true
        samples_per_shard: 500
num_classes: ???

pipeline:
    - stage_0
    - stage_1

log_dir: ???
model_dir: ???
tfrecord_dir: ???
saved_model_path: ???
checkpoints_path: ???
