# @package _group_.name

model_name: 'resnet_50_v2'
optimizer: 'Adam'
loss: 'categorical_crossentropy'
lr: 4.0e-5
lr_decay: 1.0
lr_decay_epochs: 10
regularization:
    l1: null
METRICS: ['accuracy','precision','recall']

head_layers:
    - 1024
    - 256