# @package _group_

#This should be added in the defaults of the global config
params:
  extract:
    fold_id: null
    fold_dir: null
    dataset_name: null
    num_classes: null
    threshold: 0
    color_mode: 'grayscale'
    num_channels: 3
    val_split: 0.0
    include_classes: []
    exclude_classes: ['notcataloged','notcatalogued', 'II. IDs, families uncertain', 'Unidentified']

  training:
    target_size: [512,512]
    batch_size: 16
    buffer_size: 200
    use_tfrecords: false
    samples_per_shard: 300

  testing:
    include_subsets: ['test'] # include ['train','test'] to concatenate them for testing
    eval_performance_w_sklearn: true