# @package _group_

params:
  extract:
    fold_id: 0
    fold_dir: '/home/jacob/projects/paleoai_data/paleoai_data/v0_2/data/staged_data/PNAS_in_Leaves_family_100/ksplit_2'
    dataset_name: 'PNAS_in_Leaves_family_100'
    num_classes: null
    threshold: 100
