# @package _group_

fold_dir: '/home/jacob/projects/paleoai_data/paleoai_data/v0_2/data/staged_data/Leaves_family_50/ksplit_2'
dataset_name: 'Leaves_family_50'
num_classes: null
threshold: 50
color_mode: 'grayscale'
num_channels: 3
target_size: [512,512]
val_split: 0.1
include_classes: []
exclude_classes: ['notcataloged','notcatalogued', 'II. IDs, families uncertain', 'Unidentified']